.TH OLDFIND 1 \" -*- nroff -*-
.SH NAME
oldfind \- search for files in a directory hierarchy
.SH SYNOPSIS
.B oldfind
[\-H] [\-L] [\-P] [\-D debugopts] [\-Olevel] [path...] [expression]
.SH DESCRIPTION
The
.B oldfind
and
.B find
programs are functionally identical.  The only difference between them
is the implementation internals of how the filesystem is searched.
The
.B oldfind
binary has a recursive implementation while
.B find
uses
.BR fts (3).
The fts-based implementation will replace the recursive implementation
but for the moment both implementations are installed.
.P
The implementation which is installed as
.B find
on this system is the fts-based implementation, since the
.B \-\-without\-fts
option was not passed to the
.B configure
script when findutils was built.
.SH "SEE ALSO"
\fBfind\fP(1), \fBfts\fP(3), \fBFinding Files\fP (on-line in Info, or printed).
