#!/bin/sh
if [ -e $QNX_HOST/usr/photon/bin/find.exe ]; then
  fcmd=$QNX_HOST/usr/photon/bin/find.exe
else
  fcmd=$QNX_HOST/usr/bin/find.exe
fi
$fcmd $* \( \( -name CVS -o -name RCS -o -name .svn \) -prune -o -type f \) \
	! -name CVS ! -name RCS ! -name .svn ! -name Makefile ! -name .#\*
